// ...existing code...
export default {
  // ...existing code...
  external: [
    // ...existing external dependencies...
    '@rollup/rollup-linux-x64-gnu'
  ],
  // ...existing code...
};
// ...existing code...
